#!/usr/bin/env python3
"""Embed the web client (client/*) into a C header as gzipped PROGMEM blobs.

Run automatically from PlatformIO via extra_scripts on every build. Regenerates
src/webui/embedded_client.h only when the content actually changed so unrelated
rebuilds don't trigger firmware recompiles.

Serving gzip directly keeps the flash footprint small (the client is ~59KB raw,
~15-20KB gzipped) and avoids a filesystem entirely.
"""

import gzip
import hashlib
import os
import sys
import time

# PlatformIO pre-scripts are exec'd without __file__, so fall back to cwd
# (which is the project root when the build runs).
if "__file__" in globals():
    ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
else:
    ROOT = os.getcwd()
CLIENT_DIR = os.path.join(ROOT, "client")
OUT_DIR = os.path.join(ROOT, "src", "webui")
OUT_FILE = os.path.join(OUT_DIR, "embedded_client.h")

# Order matters for stable output. Each entry: (path, mime, c-identifier)
FILES = [
    ("index.html", "text/html", "embedded_index_html"),
    ("main.js", "application/javascript", "embedded_main_js"),
    ("style.css", "text/css", "embedded_style_css"),
]

MIMES = {"index.html": "text/html", "main.js": "application/javascript", "style.css": "text/css"}


def gzip_blob(data: bytes) -> bytes:
    # mtime=0 so identical input always produces identical bytes.
    return gzip.compress(data, compresslevel=9, mtime=0)


def c_array(name: str, blob: bytes) -> str:
    lines = [f"static const uint8_t {name}_gz[] PROGMEM = {{"]
    line = "  "
    for i, b in enumerate(blob):
        line += f"0x{b:02x},"
        if (i + 1) % 16 == 0:
            lines.append(line)
            line = "  "
    if line.strip():
        lines.append(line.rstrip(","))
    lines.append("};")
    return "\n".join(lines)


def build() -> str:
    out = []
    out.append("// Auto-generated by scripts/embed_client.py — do not edit.")
    out.append("#pragma once")
    out.append("#include <Arduino.h>")
    out.append("")
    blobs = {}
    total_raw = 0
    total_gz = 0
    for name, mime, ident in FILES:
        path = os.path.join(CLIENT_DIR, name)
        with open(path, "rb") as f:
            raw = f.read()
        blob = gzip_blob(raw)
        blobs[name] = (ident, mime, blob)
        out.append(c_array(ident, blob))
        out.append("")
        total_raw += len(raw)
        total_gz += len(blob)
    out.append("struct EmbeddedFile {")
    out.append("  const char* path;")
    out.append("  const char* mime;")
    out.append("  const uint8_t* data;")
    out.append("  size_t len;")
    out.append("};")
    out.append("")
    out.append("static const EmbeddedFile embeddedFiles[] = {")
    for name, mime, ident in FILES:
        _, _, blob = blobs[name]
        out.append(f'  {{ "/{name}", "{mime}", {ident}_gz, sizeof({ident}_gz) }},')
    out.append("};")
    out.append("static const size_t embeddedFilesCount = sizeof(embeddedFiles) / sizeof(embeddedFiles[0]);")
    out.append("")
    out.append(f"// raw={total_raw}B gz={total_gz}B")
    return "\n".join(out) + "\n"


def main() -> int:
    if not os.path.isdir(CLIENT_DIR):
        print(f"[embed_client] client dir not found: {CLIENT_DIR}", file=sys.stderr)
        return 1
    content = build()
    os.makedirs(OUT_DIR, exist_ok=True)
    try:
        with open(OUT_FILE, "r") as f:
            old = f.read()
        if old == content:
            print(f"[embed_client] unchanged: {OUT_FILE}")
            return 0
    except FileNotFoundError:
        pass
    with open(OUT_FILE, "w") as f:
        f.write(content)
    print(f"[embed_client] wrote {OUT_FILE} ({len(content)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())